### ISSUE TITLE
Error calling IWS for Terms of Use: Unexpected failure: Bad Request

### ISSUE THREAD

**Issue by Nepoxx** [recolic/microsoft-intune-archlinux#4]
I have tried to run this multiple times and I always end up with this error `ERROR Error calling IWS for Terms of Use: Unexpected failure: Bad Request` 

![image](https://github.com/recolic/microsoft-intune-archlinux/assets/1477090/46f45e12-a6b8-41f3-a92a-d1ad35f66e7f)

This is a fresh arch install (EndeavourOS)
------
Debug steps taken:

- `journalctl --user -u microsoft-identity-broker.service` -> no errors
- `sudo journalctl -u microsoft-identity-device-broker.service`-> no errors
- used `seahorse` to validate keyring being default and populated
- `ldd /usr/lib/libmsal_dbus_client.so` everything defined
- `journalctl -xe` shows same error as title (which is also shown when running `intune-portal`

**Comment by recolic** [comment]
Could you make sure you have updated `/etc/os-release` file correctly? If you did, could you reboot your computer to restart intune service (sorry I forgot the name) and try again?

**Comment by Nepoxx** [comment]
Of course!

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

I have rebooted and I get the same error :(

**Comment by Nepoxx** [comment]
> It means intune-portal realized you are not using Ubuntu

That's interesting. I'm trying to figure out how that's being done. I used lurk to trace calls and I can't figure out how it is done

[files.log](https://github.com/recolic/microsoft-intune-archlinux/files/14100400/files.log)

**Comment by recolic** [comment]
Note that lurk or strace mostly cannot tell you what happened. intune does all these checks with other systemd services, such as 

`intune-agent.socket, intune-agent.service, and microsoft-identity-broker.service`. intune-agent frontend is just showing the result.

**Comment by Nepoxx** [comment]
I got past the error by updating my `/etc/lsb_release` as mentioned [here](https://github.com/recolic/microsoft-intune-archlinux/issues/1#issuecomment-1891823353) (Although intune definitely accesses `/etc/os-release` as well). I'm stuck a bit further 
![image](https://github.com/recolic/microsoft-intune-archlinux/assets/1477090/529cdd98-023a-470e-9edc-30b0f324ee50)

```
Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Starting new device enrollment
Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Submitting enrollment request attempt=1
Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: oneauth{tag="9a8hm"}: HTTP status: 404
Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: oneauth{tag="5fsch"}: Failed to get image from Graph
Feb 02 11:43:03 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Non-retryable error encountered while attempting to enroll error=HTTP error 400: Bad Request
```

**Comment by EtskaCoding** [comment]
Hi, did you find solution to the new error "Couldn't enroll your device"? I am having the same error...

**Comment by Nepoxx** [comment]
> Hi, did you find solution to the new error "Couldn't enroll your device"? I am having the same error...

I was able to get it to work by modifying `/etc/lsb_release` and using the packages in this repo, **not** the ones from AUR. The ones in AUR use newer versions and I think MS is now using other methods to detect the OS, but that's pure speculation on my part.

Here's my lsb_release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by recolic** [comment]
> I got past the error by updating my `/etc/lsb_release` as mentioned [here](https://github.com/recolic/microsoft-intune-archlinux/issues/1#issuecomment-1891823353) (Although intune definitely accesses `/etc/os-release` as well). I'm stuck a bit further ![image](https://private-user-images.githubusercontent.com/1477090/301912880-529cdd98-023a-470e-9edc-30b0f324ee50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzEzMjYsIm5iZiI6MTcwNzQ3MTAyNiwicGF0aCI6Ii8xNDc3MDkwLzMwMTkxMjg4MC01MjljZGQ5OC0wMjNhLTQ3MGUtOWVkYy0zMGIwZjMyNGVlNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMDkzMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQwYmFhYzc2YjNjZGYwZmQ3NGNiNzVkN2IyODRiNmNhZTE0NDkxZmQ5ODdjY2JjZDI2ZDhjZmYwOTdiZGU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZcJNoafaglp3KwMjZLbQEvDlPu7BA7_vVOKjDL32NdY)
> 
> ```
> Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Starting new device enrollment
> Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Submitting enrollment request attempt=1
> Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: oneauth{tag="9a8hm"}: HTTP status: 404
> Feb 02 11:42:39 nepoxx-xps intune-portal[4598]: oneauth{tag="5fsch"}: Failed to get image from Graph
> Feb 02 11:43:03 nepoxx-xps intune-portal[4598]: enroll{device_name=nepoxx-xps version=0.0.0}: Non-retryable error encountered while attempting to enroll error=HTTP error 400: Bad Request
> ```

Note that I did enroll test on manjaro... I didn't update `/etc/lsb_release` file but the enrollment process was working perfectly fine.

That's why I was not suggesting updating this file... It looks unnecessary.

**Comment by erenoglu** [comment]
Hi, I'm stugging with this as well with latest packages from AUR. I tried lsb_release but it didn't work. 
In my case, I see following in the logs, after successful loging, so I'm wondering if my system somehow is missing some certificate:

```
2024-02-19 14:50:04  WARN get_terms_of_use:verify_server_cert: Refuting an intermediate cert due to an unrecognized public key depth=1
2024-02-19 14:50:04  WARN get_terms_of_use: Sending fatal alert BadCertificate  
```

```
2024-02-19 14:50:02  INFO get_brands: Fetching default branding and customization information
2024-02-19 14:50:03  WARN get_brands:verify_server_cert: Refuting an intermediate cert due to an unrecognized public key depth=1
2024-02-19 14:50:03  WARN get_brands: Sending fatal alert BadCertificate    
2024-02-19 14:50:03  WARN Failed to load branding/customization information
2024-02-19 14:50:03  INFO get_client{....)
2024-02-19 14:50:04  WARN get_terms_of_use:verify_server_cert: Refuting an intermediate cert due to an unrecognized public key depth=1
2024-02-19 14:50:04  WARN get_terms_of_use: Sending fatal alert BadCertificate    
2024-02-19 14:50:04 ERROR Error calling IWS for Terms of Use: Network or I/O operation failed
2024-02-19 14:50:21  INFO Attempting to shutdown the auth library
```

**Comment by recolic** [comment]
Got more information today, and put the correct solution into README.md.
