### ISSUE TITLE
Can't install Level 1 on Arch

### ISSUE THREAD

**Issue by archuser123445** [recolic/microsoft-intune-archlinux#5]
WM: Hyprland
What happens when I try to install:
[logs](https://pastebin.com/J9ztztD2)

It seems to fail to install libsdbus-c++0 as it is in conflict with sdbus-cpp.
however it is required by numerous packages such as:
geoclue-2.7.1-2  hyprlang-0.2.1-4  rtkit-0.13-2  wlroots-0.17.1-1  xdg-desktop-portal-1.18.2-1  xdg-desktop-portal-hyprland-1.3.1-2
             sdbus-cpp-1.4.0-1

If anyone could help me I would greatly appreciate it.
Thanks so much.

**Comment by recolic** [comment]
Hi I will simply remove the "conflict" line in libsdbus-c++0. It's outdated and unnecessary now.
Thanks for your information.

**Comment by recolic** [comment]
fixed by removing the useless conflict line in PKGBUILD. Please try again. Thanks
