### ISSUE TITLE
Unable to register, 400 Bad Request

### ISSUE THREAD

**Issue by rayzorben** [recolic/microsoft-intune-archlinux#7]
I deleted ~/.Microsoft and ~/.cache/intune-portal and reinstalled intune-portal multiple times but I cannot get past this point.

![image](https://github.com/recolic/microsoft-intune-archlinux/assets/7737834/c8ef5e1c-0f24-42a9-a5b0-6c61813a5323)

**Comment by recolic** [comment]
Did you reinstall intune-portal program after removing cache files?
There might be more hidden things need to be deleted, so re-installing it might clean your env better.

**Comment by recolic** [comment]
@rayzorben  sadly basing on my knowledge, there is nothing I could help... I'm also just trying to speculate and sharing my experience...

**Comment by recolic** [comment]
It looks like a Microsoft bug. I tested with latest intune-portal on ubuntu 2004, exactly same error.

It's also reported by other intune users. If you are MSFT employee, please refer to BUG 2901168 for details.

**Comment by recolic** [comment]
This problem has been fixed in latest intune-portal `1.2404.23`. I will port this release to archlinux soon.

**Comment by rayzorben** [comment]
Awesome looking forward to it!

**Comment by rayzorben** [comment]
Maybe I am jumping the gun here, but I updated the PKGBUILD myself and deleted the old folders and reinstalled, however I am getting the same error, but the `intune` daemon socket is reporting the old version. I tried a `systemctl restart intune-daemon.socket` and no luck.

```
2024-05-01 13:28:55  INFO Command line arguments args=PortalArgs { common: CommonArgs { interactive: false, socket_path: "/run/intune/daemon.socket" } } version="1.2312.35"
```

```
rm -rf ~/.Microsoft ~/.cache/intune-portal ~/.config/intune


==> Leaving fakeroot environment.
==> Finished making: intune-portal 1.2404.23-0 (Wed 01 May 2024 01:20:24 PM PDT)
==> Installing package intune-portal with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...

Package (1)    Old Version  New Version  Net Change

intune-portal  1.2312.35-0  1.2404.23-0    0.00 MiB

Total Installed Size:  26.07 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 

```

**Comment by recolic** [comment]
emm I tested on archlinux just now. I installed new intune-portal, didn't restart anything, and it just works.

![image](https://github.com/recolic/microsoft-intune-archlinux/assets/19610256/ef8e72cd-838f-4656-a22e-2679954fe25b)

**Comment by rayzorben** [comment]
When you start `intune-portal` what version are you getting here:

2024-05-01 13:28:55  INFO Command line arguments args=PortalArgs { common: CommonArgs { interactive: false, socket_path: "/run/intune/daemon.socket" } } version="1.2312.35"

**Comment by recolic** [comment]
> When you start `intune-portal` what version are you getting here:
> 
> 2024-05-01 13:28:55 INFO Command line arguments args=PortalArgs { common: CommonArgs { interactive: false, socket_path: "/run/intune/daemon.socket" } } version="1.2312.35"

2024-05-01 13:25:30  INFO Command line arguments args=PortalArgs { common: CommonArgs { interactive: false, socket_path: "/run/intune/daemon.socket" } } version="1.2404.23"

My change has been synced into this github repo. Please try installing from my new PKGBUILD.

**Comment by rayzorben** [comment]
OH MY, that worked. I am super excited, thanks!
